package zaidan_daster;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class MenuLogin extends javax.swing.JFrame {
    Connection con;
    PreparedStatement stat;
    ResultSet rs;
    koneksi k = new koneksi();
    
    public MenuLogin() {
        initComponents();
        k.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        role_box = new javax.swing.JComboBox<>();
        button_login = new javax.swing.JButton();
        tombol_exit = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_username.setBackground(new java.awt.Color(204, 204, 204));
        txt_username.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 220, 30));

        txt_password.setBackground(new java.awt.Color(204, 204, 204));
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 220, 30));

        role_box.setBackground(new java.awt.Color(204, 204, 204));
        role_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "kasir" }));
        role_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                role_boxActionPerformed(evt);
            }
        });
        getContentPane().add(role_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 120, 30));

        button_login.setBackground(new java.awt.Color(102, 0, 0));
        button_login.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        button_login.setForeground(new java.awt.Color(255, 255, 255));
        button_login.setText("Sign In");
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });
        getContentPane().add(button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, 30));

        tombol_exit.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        tombol_exit.setText("X");
        tombol_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_exitActionPerformed(evt);
            }
        });
        getContentPane().add(tombol_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/MenuLogin.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        // TODO add your handling code here:
        String username = txt_username.getText();
        String password = txt_password.getText();
        String role = role_box.getSelectedItem().toString();
        
        if(username.equals("")||password.equals("")||role.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Masukkan dengan benar!", "Error", 1);
        }else{
            try{
                this.stat = k.getCon().prepareStatement("SELECT * FROM user WHERE username=? and password=?");
                stat.setString(1, txt_username.getText());
                stat.setString(2, txt_password.getText());
                rs = stat.executeQuery();
                
                if(rs.next()){
                    String sl = rs.getString("role");
                    if(role.equalsIgnoreCase("admin")&& sl.equalsIgnoreCase("admin")){
                        MenuAdmin ma = new MenuAdmin();
                        ma.setVisible(true);
                        this.dispose();
                    }else if(role.equalsIgnoreCase("kasir")&& sl.equalsIgnoreCase("kasir")){
                        MenuKasir mk = new MenuKasir();
                        mk.setVisible(true);
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Role salah!", "Sign In Error", 1);
                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Username atau Password salah!", "Sign In Error", 1);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_button_loginActionPerformed

    private void role_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_role_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_role_boxActionPerformed

    private void tombol_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tombol_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton button_login;
    private javax.swing.JComboBox<String> role_box;
    private javax.swing.JButton tombol_exit;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
