package zaidan_daster;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

public class MenuTransaksi extends javax.swing.JFrame {
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();

    public MenuTransaksi() {
        initComponents();
        k.connect();
        refreshTable();
        refreshUserBox();
        refreshPelangganBox();
        refreshProdukBox();
    }
    
    public void refreshTable(){
        model = new DefaultTableModel();
        model.addColumn("kode_transaksi");
        model.addColumn("tgl_transaksi");
        model.addColumn("batas_waktu");
        model.addColumn("quantity");
        model.addColumn("harga_total");
        model.addColumn("status_transaksi");
        model.addColumn("tgl_bayar");
        model.addColumn("status_bayar");
        model.addColumn("kode_invoice");
        model.addColumn("id_produk");
        model.addColumn("id_pelanggan");
        model.addColumn("id_user");
        tabel_transaksi.setModel(model);
        
        try{
            this.stat = k.getCon().prepareStatement("SELECT * FROM transaksi");
            this.rs = stat.executeQuery();
            while(rs.next()){
                Object[] data = {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9),
                    rs.getString(10),
                    rs.getString(11),
                    rs.getString(12)
                };
                model.addRow(data);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        txt_quantity.setText("");
        txt_kode.setText("");
    }
    
    public void refreshUserBox(){
        try{
            this.stat = k.getCon().prepareStatement("SELECT * FROM user WHERE role = 'kasir'");
            this.rs = this.stat.executeQuery();
            while(rs.next()){
                user_box.addItem(rs.getString("id_user")+":"
                +rs.getString("nama_user"));
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void refreshPelangganBox(){
        try{
            this.stat = k.getCon().prepareStatement("SELECT * FROM pelanggan");
            this.rs = this.stat.executeQuery();
            while(rs.next()){
                pelanggan_box.addItem(rs.getString("id_pelanggan")+":"
                +rs.getString("nama_pelanggan"));
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void refreshProdukBox(){
        try{
            this.stat = k.getCon().prepareStatement("SELECT * FROM produk");
            this.rs = this.stat.executeQuery();
            while(rs.next()){
                produk_box.addItem(rs.getString("id_produk")+":"
                +rs.getString("nama_produk")+":"
                +rs.getString("harga"));
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        transaksi = new javax.swing.JLabel();
        tgl_transaksi_date = new com.toedter.calendar.JDateChooser();
        pelanggan = new javax.swing.JLabel();
        pelanggan_box = new javax.swing.JComboBox<>();
        produk = new javax.swing.JLabel();
        produk_box = new javax.swing.JComboBox<>();
        bataswaktu = new javax.swing.JLabel();
        tgl_bataswaktu_date = new com.toedter.calendar.JDateChooser();
        quantity = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        tombol_create = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        invoice = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        status_transaksi = new javax.swing.JLabel();
        transaksi_box = new javax.swing.JComboBox<>();
        bayar = new javax.swing.JLabel();
        tgl_bayar_date = new com.toedter.calendar.JDateChooser();
        status_pembayaran = new javax.swing.JLabel();
        pembayaran_box = new javax.swing.JComboBox<>();
        tombol_update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_transaksi = new javax.swing.JTable();
        user = new javax.swing.JLabel();
        user_box = new javax.swing.JComboBox<>();
        tombol_view = new javax.swing.JButton();
        tombol_exit = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        transaksi.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        transaksi.setText("TANGGAL TRANSAKSI");
        jPanel1.add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));
        jPanel1.add(tgl_transaksi_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 190, 30));

        pelanggan.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        pelanggan.setText("PELANGGAN");
        jPanel1.add(pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 30));

        jPanel1.add(pelanggan_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 190, 30));

        produk.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        produk.setText("PRODUK");
        jPanel1.add(produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        jPanel1.add(produk_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 190, 30));

        bataswaktu.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bataswaktu.setText("BATAS WAKTU");
        jPanel1.add(bataswaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, 30));
        jPanel1.add(tgl_bataswaktu_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 160, 30));

        quantity.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        quantity.setText("QUANTITY");
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, 30));
        jPanel1.add(txt_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 160, 30));

        tombol_create.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        tombol_create.setText("CREATE");
        tombol_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_createActionPerformed(evt);
            }
        });
        jPanel1.add(tombol_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        jTabbedPane1.addTab("Create Transaksi", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        invoice.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        invoice.setText("KODE INVOICE");
        jPanel2.add(invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));
        jPanel2.add(txt_kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 180, 30));

        status_transaksi.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        status_transaksi.setText("STATUS TRANSAKSI");
        jPanel2.add(status_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 30));

        transaksi_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "proses", "selesai", "diambil" }));
        jPanel2.add(transaksi_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 150, 30));

        bayar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bayar.setText("TANGGAL BAYAR");
        jPanel2.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, 30));
        jPanel2.add(tgl_bayar_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 190, 30));

        status_pembayaran.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        status_pembayaran.setText("STATUS PEMBAYARAN");
        jPanel2.add(status_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, 30));

        pembayaran_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "belum dibayar", "dibayar" }));
        jPanel2.add(pembayaran_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 160, 30));

        tombol_update.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        tombol_update.setText("UPDATE");
        tombol_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_updateActionPerformed(evt);
            }
        });
        jPanel2.add(tombol_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        jTabbedPane1.addTab("Update Transaksi", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 640, 170));

        tabel_transaksi.setBackground(new java.awt.Color(102, 0, 0));
        tabel_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        tabel_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_transaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_transaksi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 620, 100));

        user.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        user.setText("ID USER");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 30));

        getContentPane().add(user_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 140, 30));

        tombol_view.setBackground(new java.awt.Color(102, 0, 0));
        tombol_view.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        tombol_view.setForeground(new java.awt.Color(255, 255, 255));
        tombol_view.setText("VIEW");
        tombol_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_viewActionPerformed(evt);
            }
        });
        getContentPane().add(tombol_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, 30));

        tombol_exit.setBackground(new java.awt.Color(102, 0, 0));
        tombol_exit.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        tombol_exit.setForeground(new java.awt.Color(255, 255, 255));
        tombol_exit.setText("EXIT");
        tombol_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_exitActionPerformed(evt);
            }
        });
        getContentPane().add(tombol_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/MenuTransaksi.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tombol_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_updateActionPerformed
        // TODO add your handling code here:
        DateFormat dateFormat2 = new SimpleDateFormat("YYYY-MM-dd HH:mm:ss");
        try{
            String tglBayar = dateFormat2.format(tgl_bayar_date.getDate());
            String statusTransaksi = transaksi_box.getSelectedItem().toString();
            String statusBayar = pembayaran_box.getSelectedItem().toString();
            String kodeInvoice = txt_kode.getText();
            
            if(tglBayar.isEmpty()||statusTransaksi.isEmpty()||statusBayar.isEmpty()||kodeInvoice.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Masukkan dengan benar!", "Error", 1);
            }else{
                stat = k.getCon().prepareStatement("UPDATE transaksi SET tgl_bayar=?, status_transaksi=?, status_bayar=? WHERE kode_invoice=?");
                stat.setString(1, tglBayar);
                stat.setString(2, statusTransaksi);
                stat.setString(3, statusBayar);
                stat.setString(4, kodeInvoice);
                stat.executeUpdate();
                refreshTable();
                JOptionPane.showMessageDialog(null, "Data berhasil diupdate!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tombol_updateActionPerformed

    private void tombol_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_createActionPerformed
        // TODO add your handling code here:
        String inv = "";
        Date d = new Date();
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-YYYY-HH-mm-ss");
        DateFormat dateFormat2 = new SimpleDateFormat("YYYY-MM-dd HH:mm:ss");
        inv = dateFormat.format(d);
        String [] split = produk_box.getSelectedItem().toString().split(":");
        String [] split1 = pelanggan_box.getSelectedItem().toString().split(":");
        String [] split2 = user_box.getSelectedItem().toString().split(":");
        String produk = split[0];
        String idpelanggan = split1[0];
        String userid = split2[0];
//        int total = Integer.parseInt(txt_quantity.getText()) * Integer.parseInt(split[2]);
        
        try{
            if (txt_quantity.getText().isEmpty()||split[2].isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Masukkan dengan benar!", "Error", 1);
            } else {
                int quantity = Integer.parseInt(txt_quantity.getText());
                int productPrice = Integer.parseInt(split[2]);
                int total = quantity * productPrice;
            
                this.stat = k.getCon().prepareStatement("INSERT INTO transaksi VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                stat.setInt(1, 0000);
                stat.setString(2, dateFormat2.format(tgl_transaksi_date.getDate()));
                stat.setString(3, dateFormat2.format(tgl_bataswaktu_date.getDate()));
                stat.setString(4, txt_quantity.getText());
                stat.setInt(5, total);
                stat.setString(6, transaksi_box.getSelectedItem().toString());
                stat.setString(7, null);
                stat.setString(8, pembayaran_box.getSelectedItem().toString());
                stat.setString(9, inv);
                stat.setString(10, produk);
                stat.setString(11, idpelanggan);
                stat.setString(12, userid);
                stat.executeUpdate();
                refreshTable();
                JOptionPane.showMessageDialog(null, "Data berhasil ditambah!");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tombol_createActionPerformed

    private void tombol_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_exitActionPerformed
        // TODO add your handling code here:
        MenuKasir mk = new MenuKasir();
        mk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombol_exitActionPerformed

    private void tabel_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_transaksiMouseClicked
        // TODO add your handling code here:
        txt_kode.setText(model.getValueAt(tabel_transaksi.getSelectedRow(), 8).toString());
    }//GEN-LAST:event_tabel_transaksiMouseClicked

    private void tombol_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_viewActionPerformed
        // TODO add your handling code here:
       DataTransaksi dt = new DataTransaksi();
       dt.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_tombol_viewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bataswaktu;
    private javax.swing.JLabel bayar;
    private javax.swing.JLabel invoice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel pelanggan;
    private javax.swing.JComboBox<String> pelanggan_box;
    private javax.swing.JComboBox<String> pembayaran_box;
    private javax.swing.JLabel produk;
    private javax.swing.JComboBox<String> produk_box;
    private javax.swing.JLabel quantity;
    private javax.swing.JLabel status_pembayaran;
    private javax.swing.JLabel status_transaksi;
    private javax.swing.JTable tabel_transaksi;
    private com.toedter.calendar.JDateChooser tgl_bataswaktu_date;
    private com.toedter.calendar.JDateChooser tgl_bayar_date;
    private com.toedter.calendar.JDateChooser tgl_transaksi_date;
    private javax.swing.JButton tombol_create;
    private javax.swing.JButton tombol_exit;
    private javax.swing.JButton tombol_update;
    private javax.swing.JButton tombol_view;
    private javax.swing.JLabel transaksi;
    private javax.swing.JComboBox<String> transaksi_box;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JLabel user;
    private javax.swing.JComboBox<String> user_box;
    // End of variables declaration//GEN-END:variables
}
