package zaidan_daster;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MenuPelanggan extends javax.swing.JFrame {
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();
    
    public MenuPelanggan() {
        initComponents();
        k.connect();
        refreshTable();
        refreshUserBox();        
    }
    
    public void refreshTable(){
        model = new DefaultTableModel();
        model.addColumn("id_pelanggan");
        model.addColumn("nama_pelanggan");
        model.addColumn("alamat");
        model.addColumn("nomor_telpon");
        model.addColumn("id_user");
        tabel_pelanggan.setModel(model);
        
        try{
            this.stat = k.getCon().prepareStatement("SELECT * FROM pelanggan");
            this.rs = stat.executeQuery();
            while(rs.next()){
                Object[] data = {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)
                };
                model.addRow(data);
            }                
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        txt_id.setText("");
        txt_nama.setText("");
        txt_alamat.setText("");
        txt_nomor.setText("");
    }
    
    public void refreshUserBox(){
        try{
            this.stat = k.getCon().prepareStatement("SELECT * FROM user WHERE role = 'kasir'");
            this.rs = this.stat.executeQuery();
            while(rs.next()){
                user_box.addItem(rs.getString("id_user"));
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teks_judul = new javax.swing.JLabel();
        tombol_create = new javax.swing.JButton();
        tombol_update = new javax.swing.JButton();
        tombol_delete = new javax.swing.JButton();
        tombol_view = new javax.swing.JButton();
        tombol_exit = new javax.swing.JButton();
        pelanggan = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        user = new javax.swing.JLabel();
        user_box = new javax.swing.JComboBox<>();
        nama = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        alamat = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        nomor = new javax.swing.JLabel();
        txt_nomor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pelanggan = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teks_judul.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        teks_judul.setForeground(new java.awt.Color(255, 255, 255));
        teks_judul.setText("PELANGGAN");
        getContentPane().add(teks_judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, 30));

        tombol_create.setFont(new java.awt.Font("Segoe UI Black", 1, 8)); // NOI18N
        tombol_create.setText("CREATE");
        tombol_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_createActionPerformed(evt);
            }
        });
        getContentPane().add(tombol_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, -1));

        tombol_update.setFont(new java.awt.Font("Segoe UI Black", 1, 8)); // NOI18N
        tombol_update.setText("UPDATE");
        tombol_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_updateActionPerformed(evt);
            }
        });
        getContentPane().add(tombol_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, -1));

        tombol_delete.setFont(new java.awt.Font("Segoe UI Black", 1, 8)); // NOI18N
        tombol_delete.setText("DELETE");
        tombol_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(tombol_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, -1));

        tombol_view.setFont(new java.awt.Font("Segoe UI Black", 1, 8)); // NOI18N
        tombol_view.setText("VIEW");
        tombol_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_viewActionPerformed(evt);
            }
        });
        getContentPane().add(tombol_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, -1));

        tombol_exit.setFont(new java.awt.Font("Segoe UI Black", 1, 8)); // NOI18N
        tombol_exit.setText("EXIT");
        tombol_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_exitActionPerformed(evt);
            }
        });
        getContentPane().add(tombol_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 50, -1));

        pelanggan.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        pelanggan.setText("ID PELANGGAN");
        getContentPane().add(pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, 30));

        txt_id.setEnabled(false);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 100, 30));

        user.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        user.setText("ID USER");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, 30));

        user_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_boxActionPerformed(evt);
            }
        });
        getContentPane().add(user_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 180, 30));

        nama.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        nama.setText("NAMA");
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, 30));

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 350, 30));

        alamat.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        alamat.setText("ALAMAT");
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, 30));

        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });
        getContentPane().add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 350, 30));

        nomor.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        nomor.setText("NOMOR TELPON");
        getContentPane().add(nomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, 30));

        txt_nomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomorActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 190, 30));

        tabel_pelanggan.setBackground(new java.awt.Color(102, 0, 0));
        tabel_pelanggan.setForeground(new java.awt.Color(255, 255, 255));
        tabel_pelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_pelanggan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 460, 110));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Menu.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tombol_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_exitActionPerformed
        // TODO add your handling code here:
        MenuKasir mk = new MenuKasir();
        mk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombol_exitActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void tombol_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_createActionPerformed
        // TODO add your handling code here:
        try{
            this.stat = k.getCon().prepareStatement("INSERT INTO pelanggan VALUES (?, ?, ?, ?, ?)");
            stat.setInt(1, 000);
            stat.setString(2, txt_nama.getText());
            stat.setString(3, txt_alamat.getText());
            stat.setString(4, txt_nomor.getText());
            stat.setString(5, user_box.getSelectedItem().toString());
            stat.executeUpdate();
            refreshTable();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tombol_createActionPerformed

    private void tombol_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_updateActionPerformed
        // TODO add your handling code here:
        try{
            stat = k.getCon().prepareStatement("UPDATE pelanggan SET nama_pelanggan=?, alamat=?, nomor_telpon=?, id_user=? WHERE id_pelanggan=?");
            stat.setString(1, txt_nama.getText());
            stat.setString(2, txt_alamat.getText());
            stat.setString(3, txt_nomor.getText());
            stat.setString(4, user_box.getSelectedItem().toString());
            stat.setString(5, txt_id.getText());
            stat.executeUpdate();
            refreshTable();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tombol_updateActionPerformed

    private void tombol_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_deleteActionPerformed
        // TODO add your handling code here:
        try{
            stat = k.getCon().prepareStatement("DELETE FROM pelanggan WHERE id_pelanggan=?");
            stat.setString(1, txt_id.getText());
            stat.executeUpdate();
            refreshTable();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tombol_deleteActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void user_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_boxActionPerformed

    private void txt_nomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomorActionPerformed

    private void tabel_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pelangganMouseClicked
        // TODO add your handling code here:
        txt_id.setText(model.getValueAt(tabel_pelanggan.getSelectedRow(), 0).toString());
        txt_nama.setText(model.getValueAt(tabel_pelanggan.getSelectedRow(), 1).toString());
        txt_alamat.setText(model.getValueAt(tabel_pelanggan.getSelectedRow(), 2).toString());
        txt_nomor.setText(model.getValueAt(tabel_pelanggan.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tabel_pelangganMouseClicked

    private void tombol_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_viewActionPerformed
        // TODO add your handling code here:
        DataPelanggan dp = new DataPelanggan();
        dp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombol_viewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nomor;
    private javax.swing.JLabel pelanggan;
    private javax.swing.JTable tabel_pelanggan;
    private javax.swing.JLabel teks_judul;
    private javax.swing.JButton tombol_create;
    private javax.swing.JButton tombol_delete;
    private javax.swing.JButton tombol_exit;
    private javax.swing.JButton tombol_update;
    private javax.swing.JButton tombol_view;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nomor;
    private javax.swing.JLabel user;
    private javax.swing.JComboBox<String> user_box;
    // End of variables declaration//GEN-END:variables
}
